version: "3"

services:
  develop:
    image: node:20-slim
    restart: always
    working_dir: /usr/src/app/
    volumes:
      - .:/usr/src/app/
    ports:
      - "8080:8080"
    command: npx quartz build --serve
